trigger:
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
- master

pool:
  vmImage: 'Windows latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm test
  displayName: 'npm test'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
 - task: AzureRmWebAppDeployment@4
   inputs:
     ConnectionType: 'AzureRM'
     azureSubscription: 'Free Trial(1)(2e181315-7830-43d1-82da-d953c8549daa)'
     appType: 'webApp'
     WebAppName: 'infosys12'
     deployToSlotOrASE: true
     ResourceGroupName: 'dotnetrg'
     SlotName: 'production'
     packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
